version: 0.2
env:
 variables:
 parameter-store:
  AWS_ACCESS_KEY_ID: "AKIARTYPWWSYC3C3EPOP"
  AWS_SECRET_ACCESS_KEY: "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"
  
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 111165224112.dkr.ecr.us-east-1.amazonaws.com
     # - REPOSITORY_URI=012345678910.dkr.ecr.us-east-1.amazonaws.com/base-image
     # - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
     # - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t test .
      - docker tag test:latest 111165224112.dkr.ecr.us-east-1.amazonaws.com/test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 111165224112.dkr.ecr.us-east-1.amazonaws.com/test:latest
